# Generated by Django 3.1 on 2020-08-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='mail_address',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
