# Generated by Django 3.1.1 on 2020-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_gameuser_mail_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_one', models.CharField(max_length=20)),
                ('player_two', models.CharField(blank=True, max_length=20)),
                ('match_status', models.CharField(choices=[('MATCHING', 'MATCHING'), ('MATCHED', 'MATCHED'), ('IN_GAME', 'IN_GAME'), ('DONE', 'DONE'), ('ERROR', 'ERROR')], max_length=10)),
            ],
            options={
                'ordering': ['match_id'],
            },
        ),
        migrations.DeleteModel(
            name='GameUser',
        ),
    ]
